### ISSUE TITLE
Expose _rawSearchParameters in Search Results?

### ISSUE THREAD

**Issue by vvo** [algolia/algoliasearch-helper-js#541] opened 2017-10-06 09:20 UTC
Use case: on an InstantSearch.js website, I want to provide a "download all" button which would allow the user to download an export of the whole result set (not just page 1).

For this I thought we could:
- take the raw search parameters sent to the JavaScript client for the filtered hits request (first request of the helper if I am not mistaken?)
- send those raw search parameters to a server side route that would then be used to export and send the result to the user

Today we are exposing the raw search results, it has the "params" stringified to Algolia (but we can't reuse them in an API client).

I am wondering if maybe we should allow API clients to be called with this stringified list of parameters (so that you don't even have to translate JSON like structures between languages, just use the stringified params to make a query).

Let me know what you think.

**Comment by bobylito** [comment] 2017-10-06 09:26
I think you got something here 👍

We already keep a ref to the state in the results (for other purposes), I'm not sure it's great to also keep the resolved queries. So what about adding a new method that will transform 'on demand' the state into the queries. The transformation is deterministic so there is no chance that we end up with something that we actually send.

I think it's the perfect place in the SearchResults, very nice idea.

**Comment by vvo** [comment] 2017-10-06 09:27
> So what about adding a new method that will transform 'on demand' the state into the queries

Yes that's a good idea, this would be really useful for the download button case.

**Comment by vvo** [comment] 2017-10-06 09:28
In the meantime, for the user request, I did: https://jsfiddle.net/s3ap8pew/1/

**Comment by Haroenv** [comment] 2019-07-11 15:29
duplicate of algolia/instantsearch#5707

**Closed by Haroenv** 2019-07-11 15:29 UTC
