### ISSUE TITLE
Use of wildcard in facets not working

### ISSUE THREAD

**Issue by mapolonio** [algolia/algoliasearch-helper-js#607] opened 2018-05-15 13:37 UTC
Hi, I'm trying to retrieve all the facets of the result set by querying with 
```
{
  facets: ['*'],
  ...
}
```
I'm getting a result with an empty array in the `facets` key.
Is the use of wildcard supported?

According to this: https://www.algolia.com/doc/guides/searching/faceting/?language=javascript#retrieving-facets it should work.

Example: https://codepen.io/mapolonio/pen/OZoyKM

**Comment by bobylito** [comment] 2018-05-16 13:29
Hi there, indeed it's not supported because the helper builds on top of the facets to let you do disjunctive and hierarchical facets.

**Comment by bobylito** [comment] 2018-05-18 10:43
@mapolonio We'd be happy to hear more from you :)

**Comment by mapolonio** [comment] 2018-05-18 13:25
Weel, I'm sorry to hear it is not supported. Do you have any advice for my case?
The problem is this: I have an index with houndreds of thousands of items, each of them has a `retailFacets` attribute that contains nested attributes, like

```
item: {
   ...some attributes,
   retailFacets: {
     color: red,
     size: 35cm,
     weight: 1k,
     ....
  }
}
```

inside `retailFacets` can be anything, as the items belong to diverse categories. You could find computer related facets and also clothing related facets, and many more. So, as the user selects certain categories on the GUI, we would like to present the concerning `retailFacets` without having to declare them one by one in the search configuration.

The reason we are using the Helper is because it was an already included dependency in the project, and for this precise matter we are discussing if we need to change to another library.

**Comment by Haroenv** [comment] 2019-05-14 09:11
just noticed this is a duplicate of algolia/instantsearch#5723

**Closed by Haroenv** 2019-05-14 09:11 UTC
