### ISSUE TITLE
Query multiple Indexes

### ISSUE THREAD

**Issue by mspivak** [algolia/algoliasearch-helper-js#271] opened 2016-01-02 13:11 UTC
I want to mix elements from two different indexes in my results. Using the JS client I was able to do it like this: https://github.com/algolia/algoliasearch-client-js#multiple-queries

Is there a way to do it with the much more featured JS helper?

**Comment by bobylito** [comment] 2016-02-01 10:23
Duplicate of #270

**Closed by bobylito** 2016-02-01 10:23 UTC
