### ISSUE TITLE
Throw on unsupported parameter

### ISSUE THREAD

**Issue by vvo** [algolia/algoliasearch-helper-js#200] opened 2015-09-02 15:09 UTC
We have been getting issues on new parameters being used and not yet available on the helper.

Right now we were silently failing making it hard to understand what's going on, following #198 we should throw in V3. Why V3? Because this could now possibly break a good number of implementations and websites.

BTW @bobylito can you re explain why do we need to declare all of the parameters explicitly instead of doing `forEach(params, param => this.paramName = this.paramValue)`?

**Comment by olance** [comment] 2015-11-09 12:52
hey I bumped into the problem trying to use an in-beta parameter – it's being rejected by the helper as it is not listed in the supported parameters.

@pixelastic suggested we remove the whole parameters whitelist mechanism and just be sure we have a way to properly inject URL params correctly when a known parameter is added to the query.

Is it completely agreed upon or should we discuss it more (maybe in a separate issue)?
I'll be happy to work on a PR to do this!

**Comment by bobylito** [comment] 2015-11-09 15:23
btw this is a algoliasearch-helper issue.

We use a white list because : 
  - documentation : when I first used Algolia I couldn't find easily a proper documentation of the parameters so this is a way to document them 
  - it's more problematic to have silently failing parameters added parameters (I know now that this is not really true, since the rest API will return an error if a parameter is incorrect).

Two be honest there are two cases : 
  - the beta/private parameters that we don't want to appear in any documentation
  - the missing implementations

For the first one, we don't want to document them, so we must have a way to use them. Either by removing the white list or providing a custom method to add those kind of parameters. But for the second case, the problem is on our side, we have to make sure that any new parameter is handled (and this is the responsability of everyone and PR are very welcome :D)

**Comment by pixelastic** [comment] 2015-11-10 09:39
I'm ok with adding another method, something like `setBetaParameter` that lets user pass any parameter, without any check. For real, well documented parameters, they'll have to be added to the whitelist (and documented).

**Comment by olance** [comment] 2015-11-11 09:54
Isn't it a bit weird to have a method that plainly shows that we "hide" some parameters?

And when a beta parameter becomes public/documented, what happens to the existing code that use `setBetaParameter` to use it? Devs will have to change it to `setQueryParameter` if they want full support of this param (thinking about the URL serialization).

I'm completely OK with the whitelist... so wouldn't it be better to have a way to easily extend this whitelist with new parameters from the "outside" so that a single method can be used to add parameters to the query ?

**Comment by vvo** [comment] 2015-11-12 10:10
I was first for the "throw" thing but then I feel this whole issue will continue to slow us down and bug us from time to time.

Right now I think you can use unknown parameters but not everywhere, like setQueryParameter will not accept it I think reading the code and tests.

The helper is currently the only library (given all api clients) that is not able to receive unknown parameters.

Reading this issue and the multiple people that had it I do think we should just accept unknown parameters in the helper and let the API server handle the errors.

Otherwise it will slow us down on the long run because everytime we do a beta parameter then it's not usable, we can get some support from beta selected customers etc.. What do you think?

**Comment by Jerskouille** [comment] 2015-11-12 10:42
Actually, isn't the whitelist already existing with the URL shortener logic? :)

**Comment by bobylito** [comment] 2015-11-12 10:59
> The helper is currently the only library (given all api clients) that is not able to receive unknown parameters

The helper is not a client. By its very nature it is closer to the API.

I think going away from the whitelist/definition of all the parameters is a regression.

**Comment by pixelastic** [comment] 2015-11-12 11:11
It's beta, and we clearly show it in the method name, so this is not really hiding parameters, just telling the developer "you can use it, but be careful, the implementation might change".

So this is expected that the beta calls should then move to the official method/whiteliste once we officially release them.

**Comment by vvo** [comment] 2015-11-12 11:13
> So this is expected that the beta calls should then move to the official method/whiteliste once we officially release them.

Once we release the new parameter out of beta, I am not sure people will change their calls from setBetaParameter to setQueryParameter. Why would you change some working code for the sake of respsecting the underlying annoucement of a no more beta parameter? Does not make a lot of sense.

> I think going away from the whitelist/definition of all the parameters is a regression.

Can you precise why it would be a regression (would it break some code?).

**Comment by pixelastic** [comment] 2015-11-12 11:17
@vvo: I was thinking about the url sync, that only works with the whitelist. It would be expected that when testing beta parameters, not all features will be included at first. Sure, if people continue using the `setBetaParameters`, most of the things will continue to work, and that's ok.

**Comment by vvo** [comment] 2015-11-12 11:24
> Sure, if people continue using the setBetaParameters, most of the things will continue to work, and that's ok.

That's ok = it works but we are inserting a temporary useless call to them. A new developer will come to their codebase and say "OH! You are using an Algolia beta parameter?" etc..

**Comment by pixelastic** [comment] 2015-11-12 11:29
Yes, and I see it as a good thing. This way you can clearly see in the code that you're using an edge parameter and undocumented feature, instead of having it merged with the classical options and you not being able to find any documentation on it.

What would you suggest instead?

**Comment by bobylito** [comment] 2015-11-12 11:31
Beta parameters don't happen often, and chances are that it may not be deployed everywhere. Also it may change (beta)

**Comment by vvo** [comment] 2015-11-12 12:35
> What would you suggest instead?

Let parameters go through the API and let the API handle the "bad parameter" issue (it's already done).

Most beta parameters we introduce them privately with some clients. It requires an update of the helper (did one or two already just for it) if they are using it.

We faced this 2-3 times + the times where ourselves are struggling with a beta parameter we want to test internally and can't because blocked from the helper.

**Comment by vvo** [comment] 2015-11-12 12:36
> Beta parameters don't happen often, and chances are that it may not be deployed everywhere. Also it may change (beta)

Yep agree but we do not announce them publicly, we inform some of the beta testers of the availability of them. Then they open support tickets because they cannot use them.

**Closed** 2016-02-19 11:27 UTC
Labels: enhancement, in progress, To be released soon :)
