### ISSUE TITLE
distinct=undefined is sent to the API if distinct is not set

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-helper-js#112] opened 2015-06-21 19:39 UTC
distinct=undefined is sent to the API if distinct is not set, generating a 400 error.

**Comment by bobylito** [comment] 2015-06-22 08:52
Can't reproduce, maybe related to 2.1.0 and fixed in 2.1.1.

**Comment by bobylito** [comment] 2015-06-22 15:06
I just reproduced this bug. Working on it!

**Closed** 2015-06-29 07:55 UTC
Labels: bug, in progress, major
