### ISSUE TITLE
Removing of refinements

### ISSUE THREAD

**Issue by maxiloc** [algolia/algoliasearch-helper-js#42] opened 2015-04-07 12:47 UTC
It be nice to be able to remove all refinements for a particular facet (conjunctive or disjunctive) without having to modify the helper refinements object from outside the helper.

**Comment by bobylito** [comment] 2015-04-07 12:57
Thanks @maxiloc! This is by far the most requested feature. And I just experience what makes it so necessary - if you modify the internals without the control of the helper functions, it might not get what it expected, and thus miserably fail with errors.

**Comment by bobylito** [comment] 2015-04-07 12:59
And this is a duplicate of #25. So I'll close this :)

**Closed by bobylito** 2015-04-07 12:59 UTC
Labels: duplicate
