### ISSUE TITLE
Uncaught SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by mspivak** [algolia/algoliasearch-helper-js#277] opened 2016-02-05 21:15 UTC
I sometimes get the following two errors on a row when requesting paginated results (It never happens when I request the first page, but frequently when I request the following ones. Of course, the request fails.

- Uncaught SyntaxError: missing ) after argument list algoliasearch.helper.js:227
- Uncaught AlgoliaSearchJSONPScriptFailError: <script> was loaded but did not call our provided callback

**Comment by vvo** [comment] 2016-02-05 21:19
Hi msprivak, could you try to get the correponding networking call that failed? It should be in either scripts or XHRs from the network tab in dev tools.

Once you have it copy paste the response or any info that could help us. You can also do a "copy as curl" and paste it here if the api key is a search only key, that's ok.

**Comment by mspivak** [comment] 2016-02-05 23:24
Here's the curl request generated by the helper:

`curl 'http://c2-use-2.algolianet.com/1/indexes/*/queries?x-algolia-api-key={{REMOVED INTENTIONALLY}}&x-algolia-application-id=I4QQGQIX64&x-algolia-agent=Algolia%20for%20AngularJS%203.10.2' -H 'accept: application/json' -H 'Referer: http://supoc.com:9006/products?category=1' -H 'Origin: http://supoc.com:9006' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36' -H 'content-type: application/x-www-form-urlencoded' --data '{"requests":[{"indexName":"products_local","params":"query=&hitsPerPage=21&page=1&facets=%5B%22vendor_id%22%2C%22brand%22%2C%22is_deal%22%2C%22category_id%22%2C%22unit_price%22%5D&tagFilters=&facetFilters=%5B%5B%22category_id%3A1%22%2C%22category_id%3A2%22%2C%22category_id%3A28%22%2C%22category_id%3A3%22%2C%22category_id%3A4%22%2C%22category_id%3A5%22%2C%22category_id%3A6%22%2C%22category_id%3A7%22%2C%22category_id%3A8%22%2C%22category_id%3A9%22%2C%22category_id%3A10%22%2C%22category_id%3A11%22%2C%22category_id%3A12%22%2C%22category_id%3A13%22%2C%22category_id%3A14%22%2C%22category_id%3A15%22%2C%22category_id%3A16%22%2C%22category_id%3A17%22%2C%22category_id%3A18%22%2C%22category_id%3A19%22%2C%22category_id%3A20%22%2C%22category_id%3A21%22%2C%22category_id%3A22%22%2C%22category_id%3A23%22%2C%22category_id%3A24%22%2C%22category_id%3A25%22%2C%22category_id%3A26%22%2C%22category_id%3A27%22%2C%22category_id%3A29%22%2C%22category_id%3A30%22%2C%22category_id%3A31%22%2C%22category_id%3A32%22%2C%22category_id%3A33%22%2C%22category_id%3A34%22%2C%22category_id%3A35%22%2C%22category_id%3A36%22%2C%22category_id%3A37%22%2C%22category_id%3A38%22%2C%22category_id%3A39%22%2C%22category_id%3A40%22%2C%22category_id%3A41%22%2C%22category_id%3A42%22%2C%22category_id%3A43%22%2C%22category_id%3A44%22%2C%22category_id%3A45%22%2C%22category_id%3A46%22%5D%5D"},{"indexName":"products_local","params":"query=&hitsPerPage=1&page=0&attributesToRetrieve=%5B%5D&attributesToHighlight=%5B%5D&attributesToSnippet=%5B%5D&tagFilters=&facets=category_id"}]}' --compressed
`

**Comment by vvo** [comment] 2016-02-06 12:21
Thanks, can you also inline what is:

> Uncaught SyntaxError: missing ) after argument list algoliasearch.helper.js:227

Because the content of this line is dependent on your build system.

Also if you are able to give us access to the running website so that we can try reproducing it, it would help (you can send it to support@algolia.com)

**Comment by bobylito** [comment] 2016-02-12 13:43
@mspivak @vvo any news on this?

**Comment by vvo** [comment] 2016-02-12 13:46
Nope we need more info on how to reproduce this

**Comment by bobylito** [comment] 2016-02-15 11:23
Well since we don't have a proper test case, I'm closing it for now. We'll reopen if we see this behavior again.

**Closed by bobylito** 2016-02-15 11:23 UTC
