### ISSUE TITLE
Indeterministic behaviour when doing query

### ISSUE THREAD

**Issue by chrisyeung1121** [algolia/algoliasearch-helper-js#149] opened 2015-07-22 04:47 UTC
Following my previous issue on #148, I found out another weird behaviour. Basically I was trying to create a booking engine that allows user to search by dates. The flow goes like this:

1. user can search `start` and `end` date, 
2. the dates are transformed to an array of unix timestamp by date in a certain timezone, so it will be like:
` [1437494400, 1437580800, 1437667200] ` for three days
3. I have stored an attribute `occupied_at_i` and add numericRefinement to all elements in the array so that `for each (n) -> helper.addNumericRefinement('occupied_at_i', '!=', n)`. 

First I am wondering if this is a correct logic to filter out products that are occupied / rented out at certain dates?

Secondly I found out that the behaviour is not as I expected. 

[I have a total of 123 records] - When I do 

`helper.clearRefinements().addNumericRefinement('occupied_at_i', '!=', 1438099200).search()` => `121 records __#correct__`
`helper.clearRefinements().addNumericRefinement('occupied_at_i', '=', 1438099200).search()` => `2 records __#correct__` 

----- 

`helper.clearRefinements().addNumericRefinement('occupied_at_i', '!=', 1438185600).search()` => `0 records __#incorrect__`
`helper.clearRefinements().addNumericRefinement('occupied_at_i', '=', 1438185600).search()` => `0 records __#incorrect__`

-------

since `'!='` and `'='` are mutually exclusive. The search query with `param: 1438185600` seems to have reflected a bug?

**Comment by bobylito** [comment] 2015-07-22 05:23
Thanks Chris.

I will investigate on that while working on #148. :)

**Comment by bobylito** [comment] 2015-08-04 09:21
Did some tests and can't reproduce this behaviour. Waiting for more informations.

**Comment by redox** [comment] 2015-09-11 06:33
I think we can close this once since we've refactored the way the numerical refinements are working in the 2.3.0 release. Please reopen it if you still have the issue!

**Closed by redox** 2015-09-11 06:33 UTC
Labels: bug, Clarifications needed
